#!/bin/bash

# Cache miss rate (line 212 or 222, item 2 of stats.txt)
for d in /home/warehouse/shannon.coupland/cse560m/hw4/sims/*/ ; do
    path="${d}stats.txt"
    dir="${d#/*/*/*/*/*/*/}"
    num="$(awk 'NR==608 {printf $2}' $path)"
    num2="$(awk 'NR==599 {printf $2}' $path)"
    printf "${dir%/},${num},${num2}\n" >> insts_issued.csv
done
